quarkus:
  log:
    # Note: Allow trace logging to be switched on at runtime but don't enable it by default
    level: INFO
    min-level: TRACE
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,S} %X{correlationId} %-5p - [%c{3.}] (%t) %s%e%n"

    category:
      "org.incept5":
        level: DEBUG
      "com.github.kagkarlsson.scheduler":
        level: DEBUG
      "org.incept5.http.interceptors":
        level: TRACE

